repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version: https://github.com/astral-sh/ruff/releases
    rev: v0.16.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
